### ISSUE TITLE
Windows 7 Ultimate

### ISSUE THREAD

**Issue by derwin12** [stojy/ClrVpin#26]
Doesnt start, doesnt show a window ..

After initial install it complained about not finding the framework and would I like to download. It wasnt clear (to me) which one to download so I downloaded a couple of things.

Now when I click the icon to start it just does nothing - but closes.
Any logs? anything I can check to see what is going on?

It works fine on my normal desktop (ie not by cab machine)

**Comment by derwin12** [comment]
Found that going back to 2.0, 2,1, and 2.2 all worked fine. I am seeming some memory dmp files whenever I try to run this 2.3 version.

**Comment by stojy** [comment]
hi @derwin12, sorry to hear that it doesn't start.

The clrvpin installer will redirect you to Microsoft's download site for .net 6, but unfortunately they don't make it particularly clear which variant is required.. and sadly it's not the first option either.  It's the 'desktop' version that's required, ideally the x64 version if you're running Win7 in 64 bit mode.  There's some setup instructions [here] (https://github.com/stojy/ClrVpin/wiki/Setup) that might help.
![image](https://user-images.githubusercontent.com/11408611/162563666-b52b1398-a0ec-4164-a400-04c2e469ab82.png)

Regarding logging, there's 2 locations..
1. If ClrVpin managed to start, then it's logs are here: %programdata%\clrvpin\logs --> which on my Win10 machine resolves to here.. C:\ProgramData\ClrVpin\logs
2. If ClrVpin fails to start, then it'll be logged in 'event viewer' (you can type that in your start menu search).  Here's an example (not from ClrVpin) of the sort of error I'd expect to see if it fails to start due to missing dependency (e.g. wrong .net version).
<img width="663" alt="image" src="https://user-images.githubusercontent.com/11408611/162564139-3a1693b1-3550-48c5-9133-a9a267d72709.png">

If you post them, then I'm sure it'll be easy to fix :)

**Comment by stojy** [comment]
If it helps, here is a direct link to the latest .net6 desktop installer from MS.. [v6.0.3](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer)

Which is the same version I currently have installed on my Win10 machine.

**Comment by derwin12** [comment]
That did it .. i wasnt installing the right .net part.. (2.3.1 works)
