### ISSUE TITLE
Incorrect mod date being used in the scanner?

### ISSUE THREAD

**Issue by derwin12** [stojy/ClrVpin#32]
Again a noob with your tool but going thru the logs and here is just one example of confusing dates/errors:
```
Fixed Game Created Time          index=0398 name='Elvira's House Of Horro' game.createdAt '21-08-21 18:00:00' < maxCreatedAt '15-03-22 07:16:10'  
Fixed Game Updated Time Too Low  index=0398 name='Elvira's House Of Horro' game.updatedAt '21-08-21 18:00:00' < maxUpdatedAt '15-03-22 07:16:15'  
Fixed Wrong Url                  index=0398 name='Elvira's House Of Horro' type=TableFiles url=https://vpuniverse.com/forums/files/file/7336-elvira-limited-edition/  
```

So from the log, it would appear that the file I have is out of date. I have '2021 and it says there is a new one from '2022
The file is found at vpuniverse. That file is '2021. So where is this '2022 date coming from that would be flagging the table to be out of date?

![image](https://user-images.githubusercontent.com/4643499/163035099-e77a66c7-43a0-4964-8433-c3b40a71898b.png)

Looking at the vps - it would appear to be from the backglass? Is that the what is happening? Is the scanner checking against the wrong date?

![image](https://user-images.githubusercontent.com/4643499/163035308-067b78bc-4c4f-4b70-aea7-81b9ff55ab71.png)

**Comment by stojy** [comment]
Definitely not a noob question.  There's a few things going on here.

Firstly, the importer feature you're using only checks the online source from VPS.  It doesn't cross reference that information against your local file collection to alert for any 'out of date' files.  This feature is effectively the next thing on my list (refer #25).

Until I get around to implementing #25, the recommended usage is to use importer to identify 'out of date' files by applying an 'updated from' in the filter that matches the last time you updated yoru collection with new content.  For example..
<img width="527" alt="image" src="https://user-images.githubusercontent.com/11408611/163207063-c74aeba6-3200-435d-8a03-040c94934c01.png">

Secondly, in order for the 'updated from' to work correctly I've had to sanitize some of the data from the VPS feed.  Whilst it's an awesome source of data, it unfortunately has a few 'quirks' where the data isn't quite correct.  You can see a summary in the statistics tab, for example..
![image](https://user-images.githubusercontent.com/11408611/163207968-8403889d-a546-411f-981d-c2133caef96e.png)

It's exactly was you've described, the top level (game) has the 'last updated' set as 29/11/21.. which isn't correct because the backglass was updated on 15/3/22.  So in order to make the ClrVpin 'updated from' feature to work I've made some tweaks to the data feed.

FYI, I've had to do similar fixes for other content fields like invalid URLs.

And lastly, to make it clear which content type(s) (e.g. backglass, table, dmd, etc) have actually been updated relative to the 'updated from' criteria, it's been marked in orange color.  For example..
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/11408611/163209890-b5767cdc-ec80-489d-98b7-2592558549ea.png">

**Comment by stojy** [comment]
Perhaps if the the 'fixed game XXXX' logs are confusing.. I might just drop them from the logs tab.  Especially as they're not particularly useful to the end user anyway.

**Comment by stojy** [comment]
Seeing as you're finding the logs useful, I'll make a note to mark those VPS sanitising logs as 'info only' seeing as they don't add any real user benefit.

The VPS google sheets is now obsolete and no longer maintained I believe.  It's been replaced by the json feed used by the newer VPS web site, which is the the exact same feed I use for ClrVpin (and subsequently sanitize) as they have thankfully open sourced it :)

I'll be sure to check out some of your tables.

**Comment by stojy** [comment]
Regarding your 3yr old collection, you could in theory set the 'updated form' to 2019 and then you would see just those tables that have been updated since.  Assuming of course the VPS feed is 100% correct.
